#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/agent/source/repos/CPSC427-2023W-T1/Team17-DefiantMortals-TitansTrial/"
#define PROJECT_SOURCE_DIR "C:/Users/Intellij IDEA/Desktop/427/Projects/"
