#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "D:/Storage/Folders/UBC CPSC/Current UBC/Cpsc 427/project/Team17-DefiantMortals-TitansTrial/"
